{
 "title": "Ewok Counters",
 "tags": [ "cvu" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "resolution",
    "query": "1s,10s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cvu",
    "query": "show tag values with key=\"cvu_name\""
   },
   {
    "name": "cvu_port",
    "label": "cVu port name",
    "query": "show tag values with key=\"cvu_port_name\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center style=\"background-color:black;padding:1rem\"><a href=\"http://www.cpacketnetworks.com\" target=\"_new\"><img width=\"220px\" src=\"/static/images/cpacket_white_text.svg\"></a></center> "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$cvu counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Ingress Total Port Bytes $cvu",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_cvu_port_name ($tag_cvu_port_id)",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "cvu_name" ], "type": "tag" },
      { "params": [ "cvu_ip" ], "type": "tag" },
      { "params": [ "cvu_port_name" ], "type": "tag" },
      { "params": [ "cvu_port_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "port_counters",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "counter_direction", "operator": "=", "value": "ingress" },
      { "condition": "AND", "key": "cvu_name", "operator": "=~", "value": "/^$cvu$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress Total Port Bytes $cvu",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_cvu_port_name ($tag_cvu_port_id)",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "cvu_name" ], "type": "tag" },
      { "params": [ "cvu_ip" ], "type": "tag" },
      { "params": [ "cvu_port_name" ], "type": "tag" },
      { "params": [ "cvu_port_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "port_counters",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "counter_direction", "operator": "=", "value": "egress" },
      { "condition": "AND", "key": "cvu_name", "operator": "=~", "value": "/^$cvu$/" }
     ]
    }
   ]
  },
  {
   "title": "Error Counter Distribution $cvu",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "alias": "$tag_cvu_name --> $tag_error_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cvu_name" ], "type": "tag" },
      { "params": [ "error_type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvu_error_counters",
     "select": [
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cvu_name", "operator": "=~", "value": "/^$cvu$/" }
     ]
    }
   ]
  },
  {
   "title": "Port Counters for $cvu",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Packet Per Second $tag_destination_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cvu_port_name" ], "type": "tag" },
      { "params": [ "counter_direction" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "port_counters",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "packets" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cvu_name", "operator": "=~", "value": "/^$cvu$/" }
     ]
    }
   ]
  },
  {
   "title": "Error Counters $cvu",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "Port: $tag_cvu_name : $tag_error_type port: $tag_cvu_port_id",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "cvu_name" ], "type": "tag" },
      { "params": [ "cvu_ip" ], "type": "tag" },
      { "params": [ "error_type" ], "type": "tag" },
      { "params": [ "cvu_port_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvu_error_counters",
     "select": [
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cvu_name", "operator": "=~", "value": "/^$cvu$/" }
     ]
    }
   ]
  },
  {
   "title": "TCP Flags $cvu",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_cvu_name --> $tag_tcp_flag",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "cvu_name" ], "type": "tag" },
      { "params": [ "tcp_flag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tcp_flags_counters",
     "select": [
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cvu_name", "operator": "=~", "value": "/^$cvu$/" }
     ]
    }
   ]
  },
  {
   "title": "Layer 3 Packets $cvu",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_cvu_name --> $tag_layer_3_protocol $tag_counter_direction",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "cvu_name" ], "type": "tag" },
      { "params": [ "layer_3_protocol" ], "type": "tag" },
      { "params": [ "counter_direction" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "layer_3_counters",
     "select": [
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cvu_name", "operator": "=~", "value": "/^$cvu$/" }
     ]
    }
   ]
  },
  {
   "title": "Layer 4 Counters Packets $cvu",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_cvu_name --> $tag_layer_4_protocol",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "cvu_name" ], "type": "tag" },
      { "params": [ "layer_4_protocol" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "layer_4_counters",
     "select": [
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cvu_name", "operator": "=~", "value": "/^$cvu$/" }
     ]
    }
   ]
  },
  {
   "title": "Layer 4 Counters Packets $cvu",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 26 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "alias": "$tag_cvu_name --> $tag_layer_4_protocol",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cvu_name" ], "type": "tag" },
      { "params": [ "layer_4_protocol" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "layer_4_counters",
     "select": [
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cvu_name", "operator": "=~", "value": "/^$cvu$/" }
     ]
    }
   ]
  },
  {
   "title": "Rule Counters (stacked) $cvu",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_cvu_name --> Policy: $tag_policy_id, Rule : $tag_rule_id",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "cvu_name" ], "type": "tag" },
      { "params": [ "rule_id" ], "type": "tag" },
      { "params": [ "policy_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvu_rule_counters",
     "select": [
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cvu_name", "operator": "=~", "value": "/^$cvu$/" }
     ]
    }
   ]
  },
  {
   "title": "Packet Counts $cvu",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_cvu_port_name ($tag_cvu_port_id)",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "cvu_name" ], "type": "tag" },
      { "params": [ "cvu_ip" ], "type": "tag" },
      { "params": [ "cvu_port_name" ], "type": "tag" },
      { "params": [ "cvu_port_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "port_counters",
     "select": [
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "counter_direction", "operator": "=", "value": "ingress" },
      { "condition": "AND", "key": "cvu_name", "operator": "=~", "value": "/^$cvu$/" }
     ]
    }
   ]
  },
  {
   "title": "Rule Counters $cvu",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 37 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_cvu_name --> Policy: $tag_policy_id",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "cvu_name" ], "type": "tag" },
      { "params": [ "policy_id" ], "type": "tag" },
      { "params": [ "rule_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvu_rule_counters",
     "select": [
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cvu_name", "operator": "=~", "value": "/^$cvu$/" }
     ]
    }
   ]
  },
  {
   "title": "TCP Flags Packets",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_cvu_name -->  $tag_tcp_flag ($tag_direction)",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "cvu_name" ], "type": "tag" },
      { "params": [ "tcp_flag" ], "type": "tag" },
      { "params": [ "direction" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tcp_flags_counters",
     "select": [
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "Frame Sizes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Ingress Port Packets  $cvu_port",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 60 },
   "repeat": "cvu_port",
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_cvu_name  ($tag_direction)",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "cvu_name" ], "type": "tag" },
      { "params": [ "cvu_ip" ], "type": "tag" },
      { "params": [ "cvu_port_name" ], "type": "tag" },
      { "params": [ "direction" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "port_counters",
     "select": [
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cvu_port_name", "operator": "=~", "value": "/^$cvu_port$/" }
     ]
    }
   ]
  },
  {
   "title": "Frame Size Counters $cvu_port",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 60 },
   "repeat": "cvu_port",
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_cvu_name -->  $tag_frame_size ($tag_cvu_port_name $tag_direction)",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "cvu_name" ], "type": "tag" },
      { "params": [ "frame_size" ], "type": "tag" },
      { "params": [ "direction" ], "type": "tag" },
      { "params": [ "cvu_port_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "frame_size_counters",
     "select": [
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cvu_port_name", "operator": "=~", "value": "/^$cvu_port$/" }
     ]
    }
   ]
  },
  {
   "title": "Frame Size Counters $cvu_port",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 60 },
   "repeat": "cvu_port",
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "alias": "$tag_frame_size  ($tag_cvu_port_name)",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "cvu_name" ], "type": "tag" },
      { "params": [ "frame_size" ], "type": "tag" },
      { "params": [ "cvu_port_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "frame_size_counters",
     "select": [
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cvu_port_name", "operator": "=~", "value": "/^$cvu_port$/" }
     ]
    }
   ]
  }
 ]
}