{
 "title": "Analytics Performance",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "thread",
    "query": "select thread from analytics_tag"
   },
   {
    "name": "resolution",
    "query": "1s,5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Slice Time All Threads",
   "type": "table",
   "gridPos": { "h": 16, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$resolution', time) AS \"time\",\n  slice_total_time as \"slice total time\",\n  packets,\n  bytes,\n  slice_start_time as \"slice start time\",\n  buffers,\n  buffer_parsing_time as \"buffer parsing time\",\n  full_process_time as \"full processing time\",\n  tcp_nodes as \"sessions\",\n  analytics_tag.thread,\n  avg_process_time as \"average processing time\",\n  timing_errors\n   \nFROM analytics join analytics_tag on analytics.tag_id=analytics_tag.tag_id\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Buffers All Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  buffers as \"values\",\n  format('thread %s',analytics_tag.thread)\n   \nFROM analytics join analytics_tag on analytics.tag_id=analytics_tag.tag_id\nWHERE\n  analytics_tag.thread != 'shared'::varchar and\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Tree Nodes Thread: $thread",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Nodes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  flow_nodes as \"values\",\n  format('flows thread %s',analytics_tag.thread)\n   \nFROM analytics join analytics_tag on analytics.tag_id=analytics_tag.tag_id\nWHERE\n  analytics_tag.thread = $thread::varchar and\n  $__timeFilter(\"time\")\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  tcp_nodes as \"values\",\n  format('sessions thread %s',analytics_tag.thread)\n   \nFROM analytics join analytics_tag on analytics.tag_id=analytics_tag.tag_id\nWHERE\n  analytics_tag.thread = $thread::varchar and\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Process Time All Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  full_process_time as \"process-time\",\n  format('thread %s',analytics_tag.thread)\nFROM analytics join analytics_tag on analytics.tag_id=analytics_tag.tag_id\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "TCP Nodes Shared",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Nodes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  active_sessions as \"values\",\n  format('active_sessions: %s',analytics_tag.thread)\n   \nFROM analytics join analytics_tag on analytics.tag_id=analytics_tag.tag_id\nWHERE\n  analytics_tag.thread = 'shared' and\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Capture Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$resolution', time) AS \"time\",\n    (\n    CASE\n      WHEN bytes_captured >= lag(bytes_captured) OVER w\n        THEN bytes_captured - lag(bytes_captured) OVER w\n      WHEN lag(bytes_captured) OVER w IS NULL THEN NULL\n      ELSE bytes_captured\n    END\n  ) * 8 / extract(epoch from time - lag(time) OVER w) AS \"Throughput\",\n  (\n    CASE\n      WHEN packets_captured >= lag(packets_captured) OVER w\n        THEN packets_captured - lag(packets_captured) OVER w\n      WHEN lag(packets_captured) OVER w IS NULL THEN NULL\n      ELSE packets_captured\n    END\n  ) / extract(epoch from time - lag(time) OVER w) AS \"Packets per second\"\nFROM capture\nWHERE\n  $__timeFilter(\"time\")\nWINDOW w AS (ORDER BY time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Drops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",(\n    CASE\n      WHEN packets_dropped >= lag(packets_dropped) OVER w\n        THEN packets_dropped - lag(packets_dropped) OVER w\n      WHEN lag(packets_dropped) OVER w IS NULL THEN NULL\n      ELSE packets_dropped\n    END\n  ) * 8 / extract(epoch from time - lag(time) OVER w) AS \"Packets Dropped\"\nFROM capture\nWHERE\n  $__timeFilter(\"time\")\nWINDOW w AS (ORDER BY time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Enqueueing To Analytics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",(\n    CASE\n      WHEN enqueued_errors_target_0_1 >= lag(enqueued_errors_target_0_1) OVER w\n        THEN enqueued_errors_target_0_1 - lag(enqueued_errors_target_0_1) OVER w\n      WHEN lag(enqueued_errors_target_0_1) OVER w IS NULL THEN NULL\n      ELSE enqueued_errors_target_0_1\n    END\n  ) * 8 / extract(epoch from time - lag(time) OVER w) AS \"enqueue errors\"\nFROM sniffer join sniffer_tag on sniffer.tag_id=sniffer_tag.tag_id\nWHERE\n  $__timeFilter(\"time\")\nWINDOW w AS (ORDER BY time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Packets Thread: $thread",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  packets as \"values\",\n  format('thread %s',analytics_tag.thread)\n   \nFROM analytics join analytics_tag on analytics.tag_id=analytics_tag.tag_id\nWHERE\n  analytics_tag.thread = $thread::varchar and\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Behind All Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$resolution', time) AS \"time\",\n  behind as \"values\",\n  format('thread %s',analytics_tag.thread)\n   \nFROM analytics join analytics_tag on analytics.tag_id=analytics_tag.tag_id\nWHERE\n analytics_tag.thread != 'shared'::varchar and\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Processing Time All Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  avg_process_time as \"average processing time\",\n  format('thread %s',analytics_tag.thread)\nFROM analytics join analytics_tag on analytics.tag_id=analytics_tag.tag_id\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1\n"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Process Time Thread: $thread",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  avg(full_process_time) as \"process-time\",\n  avg(buffer_parsing_time) as \"buffer parsing time\",\n  avg(sessions_to_sqlite3_time) as \"session to sqlite3\",\n  avg(flows_to_sqlite3_time) as \"flows to sqlite3\"\nFROM analytics join analytics_tag on analytics.tag_id=analytics_tag.tag_id\nWHERE\n  analytics_tag.thread = $thread::varchar and\n  $__timeFilter(\"time\")\nGROUP BY analytics.time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Bytes Thread: $thread",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$resolution', time) AS \"time\",\n  bytes as \"bytes\",\n  format('thread %s',analytics_tag.thread)\n   \nFROM analytics join analytics_tag on analytics.tag_id=analytics_tag.tag_id\nWHERE\n  analytics_tag.thread = $thread::varchar and\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Slice Time All Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$resolution', time) AS \"time\",\n  slice_total_time as \"values\",\n  format('slice time thread: %s',analytics_tag.thread)\n   \nFROM analytics join analytics_tag on analytics.tag_id=analytics_tag.tag_id\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Througput Thread: $thread",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  8*bytes/analytics.slice_total_time as \"values\",\n  format('thread %s',analytics_tag.thread)\n   \nFROM analytics join analytics_tag on analytics.tag_id=analytics_tag.tag_id\nWHERE\n  analytics_tag.thread = $thread::varchar and\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Behind Thread: $thread",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$resolution', time) AS \"time\",\n  behind as \"values\",\n  format('thread %s',analytics_tag.thread)\n   \nFROM analytics join analytics_tag on analytics.tag_id=analytics_tag.tag_id\nWHERE\n  analytics_tag.thread = $thread::varchar and\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Slice Time Thread: $thread",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$resolution', time) AS \"time\",\n  slice_total_time as \"values\",\n  format('thread %s',analytics_tag.thread)\n   \nFROM analytics join analytics_tag on analytics.tag_id=analytics_tag.tag_id\nWHERE\n  analytics_tag.thread = $thread::varchar and\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Througput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  8*avg(bytes/analytics.slice_total_time)\n   \nFROM analytics join analytics_tag on analytics.tag_id=analytics_tag.tag_id\nWHERE\n  \n  $__timeFilter(\"time\")\nGROUP BY\n  analytics.time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Process Time Thread: $thread",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  buffer_parsing_time as \"buffer parsing time\"\nFROM analytics join analytics_tag on analytics.tag_id=analytics_tag.tag_id\nWHERE\n  analytics_tag.thread = $thread::varchar and\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Slice Time ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  avg(slice_total_time) as \"slice time\"\nFROM analytics join analytics_tag on analytics.tag_id=analytics_tag.tag_id\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY \n  analytics.time\nORDER BY 1"
    }
   ]
  }
 ]
}