{
 "title": "Application Collectors Details",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "resolution",
    "query": "1s,10s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "network_monitor",
    "label": "Network Monitor",
    "query": "show tag values with key=\"network_monitor_name\""
   },
   {
    "name": "ip",
    "query": "show tag values with key=~/.*_ip/   LIMIT 100"
   },
   {
    "name": "application",
    "query": "show tag values with key= application_port"
   },
   {
    "name": "vlan",
    "query": "show tag values with key=~/vlan_.*/"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center style=\"background-color:black;padding:1rem\"><a href=\"http://www.cpacketnetworks.com\" target=\"_new\"><img width=\"220px\" src=\"/static/images/cpacket_white_text.svg\"></a></center> "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Download Packets",
     "type": "cclear-pcap-panel-v2",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "alias": "<CSTOR_$tag_cstor_ip>",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "cstor_ip" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "tcp_active_sessions_4_tuple",
       "select": [
        [
         { "params": [ "active_sessions" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "HTTPS Analytics for $network_monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Handshakes",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "https",
       "select": [
        [
         { "params": [ "connections" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "TLS Version Missing",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "https",
       "select": [
        [
         { "params": [ "connections" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
        { "condition": "AND", "key": "server_hello_version_name", "operator": "=", "value": "missing" }
       ]
      }
     ]
    },
    {
     "title": "TLS-1.2",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 6, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "https",
       "select": [
        [
         { "params": [ "connections" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
        { "condition": "AND", "key": "server_hello_version_name", "operator": "=", "value": "TLS-1.2" }
       ]
      }
     ]
    },
    {
     "title": "TLS-1.1 Handshakes",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 9, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "https",
       "select": [
        [
         { "params": [ "connections" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
        { "condition": "AND", "key": "server_hello_version_name", "operator": "=", "value": "TLS-1.1" }
       ]
      }
     ]
    },
    {
     "title": "TLS-1.0 Handshakes",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 12, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "https",
       "select": [
        [
         { "params": [ "connections" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
        { "condition": "AND", "key": "server_hello_version_name", "operator": "=", "value": "TLS-1.0" }
       ]
      }
     ]
    },
    {
     "title": "Certificate Not Valid Before",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 18, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "https",
       "select": [
        [
         { "params": [ "certificate_not_valid_before" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
        { "condition": "AND", "key": "certificate_not_valid_before", "operator": ">", "value": "1633113481" }
       ]
      }
     ]
    },
    {
     "title": "Certificate Not Valid After",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "https",
       "select": [
        [
         { "params": [ "certificate_not_valid_after" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
        { "condition": "AND", "key": "certificate_not_valid_after", "operator": ">", "value": "1633113481" }
       ]
      }
     ]
    },
    {
     "title": "All Handshakes",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "https",
       "select": [
        [
         { "params": [ "connections" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "HTTPS Sessions $network_monitor",
     "type": "c-packet-networks-network-map",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_in_monitor" ], "type": "tag" },
        { "params": [ "server_in_monitor" ], "type": "tag" },
        { "params": [ "network_monitor_name" ], "type": "tag" },
        { "params": [ "client_longitude" ], "type": "tag" },
        { "params": [ "client_latitude" ], "type": "tag" },
        { "params": [ "server_longitude" ], "type": "tag" },
        { "params": [ "server_latitude" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "https",
       "select": [
        [
         { "params": [ "connections" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "connections" ], "type": "alias" }
        ],
        [
         { "params": [ "packets" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "packets" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "ICMP Analytics for: $network_monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "ICMP Analytics Details for:  $network_monitor ",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Packet Per Second $tag_destination_ip",
       "groupBy": [
        { "params": [ "requester_ip" ], "type": "tag" },
        { "params": [ "responder_ip" ], "type": "tag" },
        { "params": [ "icmp_code_description" ], "type": "tag" },
        { "params": [ "icmp_message_type_description" ], "type": "tag" },
        { "params": [ "original_destination_ip" ], "type": "tag" },
        { "params": [ "original_source_ip" ], "type": "tag" }
       ],
       "measurement": "icmp",
       "select": [
        [
         { "params": [ "packets" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
        { "condition": "AND", "key": "icmp_message_type_description", "operator": "!~", "value": "/^Echo.*/" }
       ]
      }
     ]
    },
    {
     "title": "ICMP Message Type:  $network_monitor ",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 4, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "alias": "$tag_icmp_message_type_description",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "icmp_message_type_description" ], "type": "tag" }
       ],
       "measurement": "icmp",
       "select": [
        [
         { "params": [ "packets" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "ICMP Code Types:  $network_monitor ",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 4, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "alias": "$tag_icmp_code_description",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "icmp_code_description" ], "type": "tag" }
       ],
       "measurement": "icmp",
       "select": [
        [
         { "params": [ "packets" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "ICMP Responders IP:  $network_monitor ",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 4, "x": 20, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "alias": "$tag_responder_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "responder_ip" ], "type": "tag" }
       ],
       "measurement": "icmp",
       "select": [
        [
         { "params": [ "packets" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
        { "condition": "AND", "key": "icmp_message_type_description", "operator": "!=", "value": "Echo Reply" }
       ]
      }
     ]
    },
    {
     "title": "ICMP Ping Analytics Details for:  $network_monitor ",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Packet Per Second $tag_destination_ip",
       "groupBy": [
        { "params": [ "requester_ip" ], "type": "tag" },
        { "params": [ "responder_ip" ], "type": "tag" },
        { "params": [ "requester_hostname" ], "type": "tag" },
        { "params": [ "responder_hostname" ], "type": "tag" },
        { "params": [ "icmp_message_type_description" ], "type": "tag" }
       ],
       "measurement": "icmp",
       "select": [
        [
         { "params": [ "response_time" ], "type": "field" }
        ],
        [
         { "params": [ "packets" ], "type": "field" }
        ],
        [
         { "params": [ "transactions" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
        { "condition": "AND", "key": "icmp_message_type_description", "operator": "=~", "value": "/^Echo.*/" }
       ]
      }
     ]
    },
    {
     "title": "ICMP Packets:  $network_monitor ",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_icmp_code_description",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "icmp_code_description" ], "type": "tag" }
       ],
       "measurement": "icmp",
       "select": [
        [
         { "params": [ "packets" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
        { "condition": "AND", "key": "icmp_message_type_description", "operator": "!=", "value": "Echo Reply" }
       ]
      }
     ]
    },
    {
     "title": "ICMP Responders IP:  $network_monitor ",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 4, "x": 20, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "alias": "$tag_requester_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "requester_ip" ], "type": "tag" }
       ],
       "measurement": "icmp",
       "select": [
        [
         { "params": [ "packets" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
        { "condition": "AND", "key": "icmp_message_type_description", "operator": "!=", "value": "Echo Reply" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DNS Analytics for: $network_monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "DNS Analytics Details for:  $network_monitor ",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Packet Per Second $tag_destination_ip",
     "groupBy": [
      { "params": [ "requester_ip" ], "type": "tag" },
      { "params": [ "responder_ip" ], "type": "tag" },
      { "params": [ "requester_hostname" ], "type": "tag" },
      { "params": [ "responder_hostname" ], "type": "tag" },
      { "params": [ "query_type_name" ], "type": "tag" },
      { "params": [ "transaction_id" ], "type": "tag" }
     ],
     "measurement": "dns",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" }
      ],
      [
       { "params": [ "response_time" ], "type": "field" },
       { "params": [ " / 1000000" ], "type": "math" }
      ],
      [
       { "params": [ "responses" ], "type": "field" }
      ],
      [
       { "params": [ "packets" ], "type": "field" }
      ],
      [
       { "params": [ "request_time" ], "type": "field" },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
      { "condition": "AND", "key": "query_type_name", "operator": "!=", "value": "none" }
     ]
    }
   ]
  },
  {
   "title": "DNS Responders:  $network_monitor ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_responder_hostname",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "responder_hostname" ], "type": "tag" }
     ],
     "measurement": "dns",
     "select": [
      [
       { "params": [ "responses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
     ]
    }
   ]
  },
  {
   "title": "DNS Requests Query Type:  $network_monitor ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_query_type_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "query_type_name" ], "type": "tag" }
     ],
     "measurement": "dns",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTPS Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTPS Analytics Details for:  $network_monitor ",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Packet Per Second $tag_destination_ip",
       "groupBy": [
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "server_hostname" ], "type": "tag" },
        { "params": [ "client_hostname" ], "type": "tag" },
        { "params": [ "certificate_subject" ], "type": "tag" },
        { "params": [ "handshake_accepted" ], "type": "tag" },
        { "params": [ "server_hello_version_name" ], "type": "tag" },
        { "params": [ "client_in_monitor" ], "type": "tag" },
        { "params": [ "server_in_monitor" ], "type": "tag" },
        { "params": [ "server_tls_hostname" ], "type": "tag" }
       ],
       "measurement": "https",
       "select": [
        [
         { "params": [ "certificate_not_valid_after" ], "type": "field" },
         { "params": [ "*1000" ], "type": "math" }
        ],
        [
         { "params": [ "certificate_not_valid_before" ], "type": "field" },
         { "params": [ "*1000" ], "type": "math" }
        ],
        [
         { "params": [ "connections" ], "type": "field" }
        ],
        [
         { "params": [ "packets" ], "type": "field" }
        ],
        [
         { "params": [ "response_time" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "HTTPS Analytics Details for:  IP: $ip",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Packet Per Second $tag_destination_ip",
       "groupBy": [
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "server_hostname" ], "type": "tag" },
        { "params": [ "client_hostname" ], "type": "tag" },
        { "params": [ "certificate_subject" ], "type": "tag" },
        { "params": [ "handshake_accepted" ], "type": "tag" },
        { "params": [ "server_hello_version_name" ], "type": "tag" },
        { "params": [ "server_tls_hostname" ], "type": "tag" }
       ],
       "measurement": "https",
       "select": [
        [
         { "params": [ "certificate_not_valid_after" ], "type": "field" },
         { "params": [ "*1000" ], "type": "math" }
        ],
        [
         { "params": [ "certificate_not_valid_before" ], "type": "field" },
         { "params": [ "*1000" ], "type": "math" }
        ],
        [
         { "params": [ "connections" ], "type": "field" }
        ],
        [
         { "params": [ "packets" ], "type": "field" }
        ],
        [
         { "params": [ "response_time" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "OR", "key": "client_ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Last Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "placeholder",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}