{
 "title": "DNS Collector Details",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "resolution",
    "query": "1s,10s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "network_monitor",
    "label": "Network Monitor",
    "query": "show tag values with key=\"network_monitor_name\""
   },
   {
    "name": "ip",
    "query": "show tag values with key=~/.*_ip/   LIMIT 100"
   },
   {
    "name": "application",
    "query": "show tag values with key= application_port"
   },
   {
    "name": "vlan",
    "query": "show tag values with key=~/vlan_.*/"
   },
   {
    "name": "dns_responder",
    "label": "DNS Responder",
    "query": "show tag values with key=responder_hostname"
   },
   {
    "name": "dns_requester",
    "label": "DNS Requester",
    "query": "show tag values with key=requester_hostname"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center style=\"background-color:black;padding:1rem\"><a href=\"http://www.cpacketnetworks.com\" target=\"_new\"><img width=\"220px\" src=\"/static/images/cpacket_white_text.svg\"></a></center> "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Download Packets",
     "type": "cclear-pcap-panel-v2",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "alias": "<CSTOR_$tag_cstor_ip>",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "cstor_ip" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "tcp_active_sessions_4_tuple",
       "select": [
        [
         { "params": [ "active_sessions" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DNS Analytics for: $network_monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "Total Requests for monitor: $network_monitor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dns",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Responses for monitor: $network_monitor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dns",
     "select": [
      [
       { "params": [ "responses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
     ]
    }
   ]
  },
  {
   "title": "Responses to Requests Ratio for monitor: $network_monitor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dns",
     "query": "SELECT sum(\"responses\")/sum(\"requests\") FROM \"dns\" WHERE (\"network_monitor_name\" =~ /^$network_monitor$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "responses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
     ]
    }
   ]
  },
  {
   "title": "Responses to Requests Ratio (TS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "panelId": 250 }
   ]
  },
  {
   "title": "DNS Requests by Type:  $network_monitor ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_query_type_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "query_type_name" ], "type": "tag" }
     ],
     "measurement": "dns",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
     ]
    }
   ]
  },
  {
   "title": "DNS Responses by Type:  $network_monitor ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_query_type_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "query_type_name" ], "type": "tag" }
     ],
     "measurement": "dns",
     "select": [
      [
       { "params": [ "responses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
     ]
    }
   ]
  },
  {
   "title": "DNS Responses by Domain:  $network_monitor ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_query_name_domain",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "query_name_domain" ], "type": "tag" }
     ],
     "measurement": "dns",
     "select": [
      [
       { "params": [ "responses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
     ]
    }
   ]
  },
  {
   "title": "DNS Requests by Type (TS)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "panelId": 253 }
   ]
  },
  {
   "title": "DNS Responsee by Type (TS)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "panelId": 243 }
   ]
  },
  {
   "title": "DNS Responsee by Domain (TS)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "panelId": 252 }
   ]
  },
  { "title": "DNS Specific Domain Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Requests to: $dns_responder ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_requester_ip",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "requester_ip" ], "type": "tag" }
     ],
     "measurement": "dns",
     "select": [
      [
       { "params": [ "responses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "responder_hostname", "operator": "=~", "value": "/^$dns_responder$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests to: $dns_responder (TS)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "panelId": 245 }
   ]
  },
  {
   "title": "Transactions Details for:  $dns_responder",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Packet Per Second $tag_destination_ip",
     "groupBy": [
      { "params": [ "requester_ip" ], "type": "tag" },
      { "params": [ "responder_ip" ], "type": "tag" },
      { "params": [ "requester_hostname" ], "type": "tag" },
      { "params": [ "responder_hostname" ], "type": "tag" },
      { "params": [ "query_type_name" ], "type": "tag" },
      { "params": [ "transaction_id" ], "type": "tag" }
     ],
     "measurement": "dns",
     "query": "SELECT \"requests\", \"response_time\"  / 1000000, \"responses\", \"packets\", \"request_time\"  / 1000000,  \"response_time\" - \"request_time\" as \"request delta\" FROM \"dns\" WHERE (\"responder_hostname\" =~ /^$dns_responder$/) AND $timeFilter GROUP BY \"requester_ip\", \"responder_ip\", \"requester_hostname\", \"responder_hostname\", \"query_type_name\", \"transaction_id\"",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" }
      ],
      [
       { "params": [ "response_time" ], "type": "field" },
       { "params": [ " / 1000000" ], "type": "math" }
      ],
      [
       { "params": [ "responses" ], "type": "field" }
      ],
      [
       { "params": [ "packets" ], "type": "field" }
      ],
      [
       { "params": [ "request_time" ], "type": "field" },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
      { "condition": "AND", "key": "query_type_name", "operator": "!=", "value": "none" }
     ]
    }
   ]
  },
  { "title": "DNS Transaction Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "DNS Analytics Details for:  $network_monitor ",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Packet Per Second $tag_destination_ip",
     "groupBy": [
      { "params": [ "requester_ip" ], "type": "tag" },
      { "params": [ "responder_ip" ], "type": "tag" },
      { "params": [ "requester_hostname" ], "type": "tag" },
      { "params": [ "responder_hostname" ], "type": "tag" },
      { "params": [ "query_type_name" ], "type": "tag" },
      { "params": [ "transaction_id" ], "type": "tag" }
     ],
     "measurement": "dns",
     "query": "SELECT \"requests\", \"response_time\"  / 1000000, \"responses\", \"packets\", \"request_time\"  / 1000000,  \"response_time\" - \"request_time\" as \"request delta\" FROM \"dns\" WHERE (\"network_monitor_name\" =~ /^$network_monitor$/ AND \"query_type_name\" != 'none') AND $timeFilter GROUP BY \"requester_ip\", \"responder_ip\", \"requester_hostname\", \"responder_hostname\", \"query_type_name\", \"transaction_id\"",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" }
      ],
      [
       { "params": [ "response_time" ], "type": "field" },
       { "params": [ " / 1000000" ], "type": "math" }
      ],
      [
       { "params": [ "responses" ], "type": "field" }
      ],
      [
       { "params": [ "packets" ], "type": "field" }
      ],
      [
       { "params": [ "request_time" ], "type": "field" },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
      { "condition": "AND", "key": "query_type_name", "operator": "!=", "value": "none" }
     ]
    }
   ]
  },
  { "title": "Last Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "placeholder",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}