{
 "title": "Flows Level 2 - (Sapphire w/ Network Monitor)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "resolution",
    "query": "1s,10s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "network_monitor",
    "label": "Network Monitor",
    "query": "show tag values with key=\"network_monitor_name\""
   },
   {
    "name": "ip_protocol",
    "label": "IP Protocol",
    "query": "show tag values with key=ip_protocol_name"
   },
   {
    "name": "application",
    "query": "show tag values with key= application_port"
   },
   {
    "name": "vlan",
    "query": "show tag values with key=~/vlan_.*/"
   },
   {
    "name": "ip",
    "query": "show tag values with key=~/.*_ip/   LIMIT 100"
   },
   { "name": "slimit", "label": "Limit", "query": "10,100,1000,10000,100000" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center style=\"background-color:black;padding:1rem\"><a href=\"http://www.cpacketnetworks.com\" target=\"_new\"><img width=\"220px\" src=\"/static/images/cpacket_white_text.svg\"></a></center> "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Download Packets",
     "type": "cclear-pcap-panel-v2",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "alias": "<CSTOR_$tag_cstor_ip>",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "cstor_ip" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "flow_data_4_tuple",
       "select": [
        [
         { "params": [ "bytes_per_s" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Flows Map ( IP: $ip)",
     "type": "c-packet-networks-network-map",
     "gridPos": { "h": 12, "w": 16, "x": 8, "y": 4 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "source_ip" ], "type": "tag" },
        { "params": [ "destination_ip" ], "type": "tag" },
        { "params": [ "source_in_monitor" ], "type": "tag" },
        { "params": [ "destination_in_monitor" ], "type": "tag" },
        { "params": [ "network_monitor_name" ], "type": "tag" },
        { "params": [ "source_latitude" ], "type": "tag" },
        { "params": [ "source_longitude" ], "type": "tag" },
        { "params": [ "destination_latitude" ], "type": "tag" },
        { "params": [ "destination_longitude" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flow_data_4_tuple",
       "select": [
        [
         { "params": [ "bytes_per_s" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "bytes" ], "type": "alias" }
        ]
       ],
       "slimit": "1000",
       "tags": [
        { "key": "destination_ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "OR", "key": "source_ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Flows Breakdown by Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Flows by TCP Application for Network Monitor: $network_monitor",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_application_port",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "application_port" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "flow_data_4_tuple",
     "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"client_ip\" =~ /^$ip$/ OR \"server_ip\" =~ /^$ip$/) AND $timeFilter GROUP BY time($resolution), \"server_ip\", \"client_ip\" fill(0)",
     "select": [
      [
       { "params": [ "flows" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
      { "condition": "AND", "key": "ip_protocol_name", "operator": "=", "value": "TCP" }
     ]
    }
   ]
  },
  {
   "title": "Total Flows by UDP Application for Network Monitor: $network_monitor",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_application_port",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "application_port" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "flow_data_4_tuple",
     "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"client_ip\" =~ /^$ip$/ OR \"server_ip\" =~ /^$ip$/) AND $timeFilter GROUP BY time($resolution), \"server_ip\", \"client_ip\" fill(0)",
     "select": [
      [
       { "params": [ "flows" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
      { "condition": "AND", "key": "ip_protocol_name", "operator": "=", "value": "UDP" }
     ]
    }
   ]
  },
  {
   "title": "Flow Data Overview Network Monitor: $network_monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Flows Details (protocol: $ip_protocol application: $application)",
   "type": "table",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "source_ip" ], "type": "tag" },
      { "params": [ "destination_ip" ], "type": "tag" },
      { "params": [ "ip_protocol_name" ], "type": "tag" },
      { "params": [ "application_port" ], "type": "tag" },
      { "params": [ "destination_hostname" ], "type": "tag" },
      { "params": [ "source_hostname" ], "type": "tag" },
      { "params": [ "ethertype" ], "type": "tag" },
      { "params": [ "source_in_monitor" ], "type": "tag" },
      { "params": [ "destination_in_monitor" ], "type": "tag" }
     ],
     "measurement": "flow_data_4_tuple",
     "query": "SELECT sum(\"bytes_per_s\") AS \"bytes\", sum(\"fragments\") AS \"fragments\" FROM \"flow_data_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$network_monitor$/ AND \"ip_protocol_name\" =~ /^$ip_protocol$/) AND $timeFilter GROUP BY time($interval), \"source_ip\", \"destination_ip\", \"ip_protocol_name\", \"application_port\"",
     "select": [
      [
       { "params": [ "bytes_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "fragments" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "fragments" ], "type": "alias" }
      ],
      [
       { "params": [ "flows" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "flows" ], "type": "alias" }
      ]
     ],
     "slimit": "$slimit",
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
      { "condition": "AND", "key": "ip_protocol_name", "operator": "=~", "value": "/^$ip_protocol$/" },
      { "condition": "AND", "key": "application_port", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Series Count for Network Monitor: $network_monitor",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show series cardinality  from flow_data_4_tuple ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Source IP Count for Flow Data",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG VALUES ON indicators FROM flow_data_4_tuple WITH KEY = \"source_ip\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Destination IP Count for Flow Data",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG VALUES ON indicators FROM flow_data_4_tuple WITH KEY = \"destination_ip\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Flows by Application $network_monitor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_application_port",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "application_port" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "flow_data_4_tuple",
     "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"client_ip\" =~ /^$ip$/ OR \"server_ip\" =~ /^$ip$/) AND $timeFilter GROUP BY time($resolution), \"server_ip\", \"client_ip\" fill(0)",
     "select": [
      [
       { "params": [ "flows" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
     ]
    }
   ]
  },
  {
   "title": "Data Breakdown by Application  ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "Total Data by IP Protocol for Network Monitor: $network_monitor",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_ip_protocol_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "ip_protocol_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "flow_data_4_tuple",
     "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"client_ip\" =~ /^$ip$/ OR \"server_ip\" =~ /^$ip$/) AND $timeFilter GROUP BY time($resolution), \"server_ip\", \"client_ip\" fill(0)",
     "select": [
      [
       { "params": [ "bytes_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Data by VLAN Network Monitor: $network_monitor",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    { "panelId": 272 }
   ]
  },
  {
   "title": "TS Total Data by VLAN Network Monitor: $network_monitor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_vlan_tag_outer",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "vlan_tag_outer" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "flow_data_4_tuple",
     "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"client_ip\" =~ /^$ip$/ OR \"server_ip\" =~ /^$ip$/) AND $timeFilter GROUP BY time($resolution), \"server_ip\", \"client_ip\" fill(0)",
     "select": [
      [
       { "params": [ "bytes_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
      { "condition": "AND", "key": "vlan_tag_outer", "operator": "!=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Total Data by TCP Application for Network Monitor: $network_monitor",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    { "panelId": 263 }
   ]
  },
  {
   "title": "TS Total TCP Data by Application for Network Monitor: $network_monitor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_application_port",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "application_port" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "flow_data_4_tuple",
     "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"client_ip\" =~ /^$ip$/ OR \"server_ip\" =~ /^$ip$/) AND $timeFilter GROUP BY time($resolution), \"server_ip\", \"client_ip\" fill(0)",
     "select": [
      [
       { "params": [ "bytes_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
      { "condition": "AND", "key": "ip_protocol_name", "operator": "=", "value": "TCP" }
     ]
    }
   ]
  },
  {
   "title": "TCP Data by Application for Network Monitor: $network_monitor",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_application_port",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "application_port" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "flow_data_4_tuple",
     "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"client_ip\" =~ /^$ip$/ OR \"server_ip\" =~ /^$ip$/) AND $timeFilter GROUP BY time($resolution), \"server_ip\", \"client_ip\" fill(0)",
     "select": [
      [
       { "params": [ "bytes_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Bytes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
      { "condition": "AND", "key": "ip_protocol_name", "operator": "=", "value": "TCP" }
     ]
    }
   ]
  },
  {
   "title": "Total Data by UDP Application for Network Monitor: $network_monitor",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    { "panelId": 271 }
   ]
  },
  {
   "title": "TS Total UDP Data by Application for Network Monitor: $network_monitor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_application_port",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "application_port" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "flow_data_4_tuple",
     "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"client_ip\" =~ /^$ip$/ OR \"server_ip\" =~ /^$ip$/) AND $timeFilter GROUP BY time($resolution), \"server_ip\", \"client_ip\" fill(0)",
     "select": [
      [
       { "params": [ "bytes_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
      { "condition": "AND", "key": "ip_protocol_name", "operator": "=", "value": "UDP" }
     ]
    }
   ]
  },
  {
   "title": "UDP Data by Application for Network Monitor: $network_monitor",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_application_port",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "application_port" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "flow_data_4_tuple",
     "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"client_ip\" =~ /^$ip$/ OR \"server_ip\" =~ /^$ip$/) AND $timeFilter GROUP BY time($resolution), \"server_ip\", \"client_ip\" fill(0)",
     "select": [
      [
       { "params": [ "bytes_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Bytes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
      { "condition": "AND", "key": "ip_protocol_name", "operator": "=", "value": "UDP" }
     ]
    }
   ]
  },
  {
   "title": "IP based Data (might be slow)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": " Data TS by Source IP for: $ip  (limit $slimit)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_source_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "source_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "flow_data_4_tuple",
       "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"client_ip\" =~ /^$ip$/ OR \"server_ip\" =~ /^$ip$/) AND $timeFilter GROUP BY time($resolution), \"server_ip\", \"client_ip\" fill(0)",
       "select": [
        [
         { "params": [ "bytes_per_s" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "slimit": "$slimit",
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
        { "condition": "AND", "key": "source_ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "source_ip", "operator": "!=", "value": "0.0.0.0" }
       ]
      }
     ]
    },
    {
     "title": " Data TS by Destination IP for: $ip  (limit $slimit)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_source_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "source_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "flow_data_4_tuple",
       "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"client_ip\" =~ /^$ip$/ OR \"server_ip\" =~ /^$ip$/) AND $timeFilter GROUP BY time($resolution), \"server_ip\", \"client_ip\" fill(0)",
       "select": [
        [
         { "params": [ "bytes_per_s" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "slimit": "$slimit",
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
        { "condition": "AND", "key": "destination_ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "destination_ip", "operator": "!=", "value": "0.0.0.0" }
       ]
      }
     ]
    },
    {
     "title": "TS Source Data per Application: $application ",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_source_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "source_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "flow_data_4_tuple",
       "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"client_ip\" =~ /^$ip$/ OR \"server_ip\" =~ /^$ip$/) AND $timeFilter GROUP BY time($resolution), \"server_ip\", \"client_ip\" fill(0)",
       "select": [
        [
         { "params": [ "bytes_per_s" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "slimit": "$slimit",
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
        { "condition": "AND", "key": "application_port", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "source_ip", "operator": "!=", "value": "0.0.0.0" }
       ]
      }
     ]
    },
    {
     "title": "Total Data by Source IP for: $ip  (limit $slimit)",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "format": "decbytes",
     "valueName": "total",
     "targets": [
      { "panelId": 278 }
     ]
    },
    {
     "title": "Total Data by Destination IP for: $ip (limit $slimit)",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "format": "decbytes",
     "valueName": "total",
     "targets": [
      { "panelId": 279 }
     ]
    },
    {
     "title": "Source IP for Application: $application",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "format": "decbytes",
     "valueName": "total",
     "targets": [
      { "panelId": 280 }
     ]
    }
   ]
  },
  {
   "title": "Web Server Name Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data and Flows Web Server (Source)",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 64 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "source_ip" ], "type": "tag" },
        { "params": [ "destination_ip" ], "type": "tag" },
        { "params": [ "destination_hostname" ], "type": "tag" },
        { "params": [ "source_hostname" ], "type": "tag" },
        { "params": [ "destination_tls_hostname" ], "type": "tag" },
        { "params": [ "source_tls_hostname" ], "type": "tag" }
       ],
       "measurement": "flow_data_4_tuple",
       "query": "SELECT sum(\"bytes_per_s\") AS \"bytes\", sum(\"fragments\") AS \"fragments\" FROM \"flow_data_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$network_monitor$/ AND \"ip_protocol_name\" =~ /^$ip_protocol$/) AND $timeFilter GROUP BY time($interval), \"source_ip\", \"destination_ip\", \"ip_protocol_name\", \"application_port\"",
       "select": [
        [
         { "params": [ "bytes_per_s" ], "type": "field" },
         { "params": [ "bytes" ], "type": "alias" }
        ],
        [
         { "params": [ "flows" ], "type": "field" },
         { "params": [ "flows" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
        { "condition": "AND", "key": "source_tls_hostname", "operator": "!=", "value": "none" },
        { "condition": "AND", "key": "source_tls_hostname", "operator": "!=", "value": "0.0" }
       ]
      }
     ]
    },
    {
     "title": "Web Server Data (Source) for Network Monitor: $network_monitor",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "format": "decbytes",
     "valueName": "total",
     "targets": [
      {
       "alias": "$tag_source_tls_hostname",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "source_tls_hostname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flow_data_4_tuple",
       "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"client_ip\" =~ /^$ip$/ OR \"server_ip\" =~ /^$ip$/) AND $timeFilter GROUP BY time($resolution), \"server_ip\", \"client_ip\" fill(0)",
       "select": [
        [
         { "params": [ "bytes_per_s" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
        { "condition": "AND", "key": "ip_protocol_name", "operator": "=", "value": "TCP" },
        { "condition": "AND", "key": "source_tls_hostname", "operator": "!=", "value": "none" }
       ]
      }
     ]
    },
    {
     "title": "Data and Flows Web Server (Destination)",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 75 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "source_ip" ], "type": "tag" },
        { "params": [ "destination_ip" ], "type": "tag" },
        { "params": [ "destination_hostname" ], "type": "tag" },
        { "params": [ "source_hostname" ], "type": "tag" },
        { "params": [ "destination_tls_hostname" ], "type": "tag" },
        { "params": [ "source_tls_hostname" ], "type": "tag" }
       ],
       "measurement": "flow_data_4_tuple",
       "query": "SELECT sum(\"bytes_per_s\") AS \"bytes\", sum(\"fragments\") AS \"fragments\" FROM \"flow_data_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$network_monitor$/ AND \"ip_protocol_name\" =~ /^$ip_protocol$/) AND $timeFilter GROUP BY time($interval), \"source_ip\", \"destination_ip\", \"ip_protocol_name\", \"application_port\"",
       "select": [
        [
         { "params": [ "bytes_per_s" ], "type": "field" },
         { "params": [ "bytes" ], "type": "alias" }
        ],
        [
         { "params": [ "flows" ], "type": "field" },
         { "params": [ "flows" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
        { "condition": "AND", "key": "ip_protocol_name", "operator": "=", "value": "TCP" },
        { "condition": "AND", "key": "application_port", "operator": "=", "value": "HTTPS" },
        { "condition": "AND", "key": "destination_tls_hostname", "operator": "!=", "value": "none" },
        { "condition": "AND", "key": "destination_tls_hostname", "operator": "!=", "value": "0.0" }
       ]
      }
     ]
    },
    {
     "title": "Web Server Data (Destination) for Network Monitor: $network_monitor",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "format": "decbytes",
     "valueName": "total",
     "targets": [
      {
       "alias": "$tag_destination_tls_hostname",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "destination_tls_hostname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "flow_data_4_tuple",
       "query": "SELECT sum(\"bytes_per_s\") FROM \"flow_data_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$network_monitor$/ AND \"ip_protocol_name\" = 'TCP' AND \"destination_tls_hostname\" != ''  AND \"destination_tls_hostname\" != 'none' ) AND $timeFilter GROUP BY time($resolution), \"destination_tls_hostname\" fill(none)",
       "select": [
        [
         { "params": [ "bytes_per_s" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
        { "condition": "AND", "key": "ip_protocol_name", "operator": "=", "value": "TCP" },
        { "condition": "AND", "key": "destination_tls_hostname", "operator": "!=", "value": "''" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Last Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "placeholder",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}