{
 "title": "TCP Analytics - Level 2 (Sapphire w/ Network Map)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "resolution",
    "query": "1s,10s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "network_monitor",
    "label": "Network Monitor",
    "query": "show tag values with key=\"network_monitor_name\""
   },
   {
    "name": "ip",
    "query": "show tag values with key=~/.*_ip/   LIMIT 100"
   },
   {
    "name": "application",
    "query": "show tag values with key= application_port"
   },
   {
    "name": "vlan",
    "query": "show tag values with key=~/vlan_.*/"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center style=\"background-color:black;padding:1rem\"><a href=\"http://www.cpacketnetworks.com\" target=\"_new\"><img width=\"220px\" src=\"/static/images/cpacket_white_text.svg\"></a></center> "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Download Packets",
     "type": "cclear-pcap-panel-v2",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "alias": "<CSTOR_$tag_cstor_ip>",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "cstor_ip" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "tcp_active_sessions_4_tuple",
       "select": [
        [
         { "params": [ "active_sessions" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "TCP Session Details for $network_monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "4-Tuple Active (open) TCP Sessions  $network_monitor",
   "type": "table",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Packet Per Second $tag_destination_ip",
     "groupBy": [
      { "params": [ "server_ip" ], "type": "tag" },
      { "params": [ "application_port" ], "type": "tag" },
      { "params": [ "client_ip" ], "type": "tag" },
      { "params": [ "server_hostname" ], "type": "tag" },
      { "params": [ "client_hostname" ], "type": "tag" },
      { "params": [ "network_monitor_name" ], "type": "tag" },
      { "params": [ "server_port" ], "type": "tag" },
      { "params": [ "ip_protocol_name" ], "type": "tag" }
     ],
     "measurement": "tcp_active_sessions_4_tuple",
     "select": [
      [
       { "params": [ "rtt_client_s_avg" ], "type": "field" }
      ],
      [
       { "params": [ "rtt_server_s_avg" ], "type": "field" }
      ],
      [
       { "params": [ "response_time_s_avg" ], "type": "field" }
      ],
      [
       { "params": [ "packets_server_session_avg" ], "type": "field" }
      ],
      [
       { "params": [ "packets_client_session_avg" ], "type": "field" }
      ],
      [
       { "params": [ "bytes_server_session_avg" ], "type": "field" }
      ],
      [
       { "params": [ "bytes_client_session_avg" ], "type": "field" }
      ],
      [
       { "params": [ "duration_s_max" ], "type": "field" }
      ],
      [
       { "params": [ "missing_syns" ], "type": "field" }
      ],
      [
       { "params": [ "syn_failure" ], "type": "field" }
      ],
      [
       { "params": [ "active_sessions" ], "type": "field" }
      ],
      [
       { "params": [ "synacks" ], "type": "field" }
      ],
      [
       { "params": [ "syns" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
     ]
    }
   ]
  },
  {
   "title": "4-Tuple Active (open) TCP Sessions  $network_monitor",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col $tag_client_ip ($tag_application_port, $tag_ip_protocol_name)",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "client_ip" ], "type": "tag" },
      { "params": [ "application_port" ], "type": "tag" },
      { "params": [ "ip_protocol_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tcp_active_sessions_4_tuple",
     "select": [
      [
       { "params": [ "bytes_server_session_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Server Bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_client_session_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Client Bytes" ], "type": "alias" }
      ]
     ],
     "slimit": "20",
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
     ]
    }
   ]
  },
  {
   "title": "4-Tuple Time Slice TCP  $network_monitor",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Packet Per Second $tag_destination_ip",
     "groupBy": [
      { "params": [ "server_ip" ], "type": "tag" },
      { "params": [ "application_port" ], "type": "tag" },
      { "params": [ "client_ip" ], "type": "tag" },
      { "params": [ "server_hostname" ], "type": "tag" },
      { "params": [ "client_hostname" ], "type": "tag" },
      { "params": [ "network_monitor_name" ], "type": "tag" }
     ],
     "limit": "100",
     "measurement": "tcp_4_tuple",
     "select": [
      [
       { "params": [ "retransmissions_client" ], "type": "field" }
      ],
      [
       { "params": [ "retransmissions_server" ], "type": "field" }
      ],
      [
       { "params": [ "fragments_client" ], "type": "field" }
      ],
      [
       { "params": [ "fragments_server" ], "type": "field" }
      ],
      [
       { "params": [ "packets_client" ], "type": "field" }
      ],
      [
       { "params": [ "packets_server" ], "type": "field" }
      ],
      [
       { "params": [ "gaps_client" ], "type": "field" }
      ],
      [
       { "params": [ "gaps_server" ], "type": "field" }
      ],
      [
       { "params": [ "duplicates_client" ], "type": "field" }
      ],
      [
       { "params": [ "duplicates_server" ], "type": "field" }
      ],
      [
       { "params": [ "bytes_client" ], "type": "field" }
      ],
      [
       { "params": [ "bytes_server" ], "type": "field" }
      ],
      [
       { "params": [ "syns_client" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
     ]
    }
   ]
  },
  {
   "title": "Data from Client  $network_monitor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "client: $tag_client_ip",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "client_ip" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tcp_4_tuple",
     "query": "SELECT sum(\"bytes_client\") + sum(\"bytes_server\") FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$network_monitor$/) AND $timeFilter GROUP BY time($resolution), \"server_ip\", \"client_ip\" fill(0)",
     "select": [
      [
       { "params": [ "bytes_client" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "bytes_server" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
     ]
    }
   ]
  },
  {
   "title": "TCP Sessions Map $network_monitor",
   "type": "c-packet-networks-network-map",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "client_ip" ], "type": "tag" },
      { "params": [ "server_ip" ], "type": "tag" },
      { "params": [ "client_in_monitor" ], "type": "tag" },
      { "params": [ "server_in_monitor" ], "type": "tag" },
      { "params": [ "network_monitor_name" ], "type": "tag" },
      { "params": [ "client_longitude" ], "type": "tag" },
      { "params": [ "client_latitude" ], "type": "tag" },
      { "params": [ "server_longitude" ], "type": "tag" },
      { "params": [ "server_latitude" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tcp_active_sessions_4_tuple",
     "select": [
      [
       { "params": [ "response_time_s_avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "response time" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_client_session_avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "bytes" ], "type": "alias" }
      ]
     ],
     "slimit": "1000",
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" },
      { "condition": "AND", "key": "client_ip", "operator": "!~", "value": "/^10\\..*/" }
     ]
    }
   ]
  },
  {
   "title": "TCP Session Data and Duration Details for $network_monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data for $network_monitor",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "packets" } },
     "format": "decbytes",
     "valueName": "total",
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tcp_4_tuple",
       "query": "SELECT sum(\"bytes_client\") + sum(\"bytes_server\")  FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$network_monitor$/ ) AND $timeFilter GROUP BY time($resolution), \"server_ip\", \"client_ip\" fill(none)",
       "select": [
        [
         { "params": [ "bytes_client" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Client Packets" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_server" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Server Packets" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "client_ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "OR", "key": "server_ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      }
     ]
    },
    {
     "title": "Data from Client  $network_monitor",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_4_tuple",
       "select": [
        [
         { "params": [ "bytes_client" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Client Bytes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Data from Server $network_monitor",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_4_tuple",
       "select": [
        [
         { "params": [ "bytes_server" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Server Bytes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Max Active Session Data for $network_monitor",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "packets" } },
     "format": "decbytes",
     "valueName": "max",
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tcp_active_sessions_4_tuple",
       "query": "SELECT max(\"bytes_client_session_max\") + max(\"bytes_server_session_max\") FROM \"tcp_active_sessions_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$network_monitor$/ ) AND $timeFilter GROUP BY time($resolution), \"server_ip\", \"client_ip\" fill(none)",
       "select": [
        [
         { "params": [ "bytes_client_session_max" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ],
        [
         { "params": [ "bytes_server_session_max" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "client_ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "OR", "key": "server_ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      }
     ]
    },
    {
     "title": "Max Active Session Data from Client  $network_monitor",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_active_sessions_4_tuple",
       "select": [
        [
         { "params": [ "bytes_client_session_max" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Client Bytes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Max Active Session Data from Server  $network_monitor",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_active_sessions_4_tuple",
       "select": [
        [
         { "params": [ "bytes_server_session_max" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Client Bytes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Max Active Session Duration for $network_monitor",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "packets" } },
     "format": "s",
     "valueName": "max",
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tcp_active_sessions_4_tuple",
       "query": "SELECT max(\"bytes_client_session_max\") + max(\"bytes_server_session_max\") FROM \"tcp_active_sessions_4_tuple\" WHERE (\"client_ip\" =~ /^$ip$/ OR \"server_ip\" =~ /^$ip$/) AND $timeFilter GROUP BY time($resolution), \"server_ip\", \"client_ip\" fill(none)",
       "select": [
        [
         { "params": [ "duration_s_max" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Max Duration for Active (open) Sessions $network_monitor",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_active_sessions_4_tuple",
       "select": [
        [
         { "params": [ "duration_s_max" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Max Idle Duration for Active (open) Sessions  $network_monitor",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_active_sessions_4_tuple",
       "select": [
        [
         { "params": [ "idle_s_max" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network and Application Latency Details for $network_monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mean Response Time (Network Latency) for $network_monitor",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "client: $tag_client_ip to server: $tag_server_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_active_sessions_4_tuple",
       "select": [
        [
         { "params": [ "response_time_s_avg" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Mean Server Round Trip Time (device latencty) for  $network_monitor",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$col: client: $tag_client_ip to server $tag_server_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_4_tuple",
       "select": [
        [
         { "params": [ "rtt_server_s" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Server RTT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Mean Client Round Trip Time (device latency) for  $network_monitor",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$col: client: $tag_client_ip to server $tag_server_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_4_tuple",
       "select": [
        [
         { "params": [ "rtt_client_s" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Client RTT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Active (Open) Session for $network_monitor",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_active_sessions_4_tuple",
       "select": [
        [
         { "params": [ "active_sessions" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Finished Sessions for $network_monitor",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_active_sessions_4_tuple",
       "select": [
        [
         { "params": [ "finished_sessions" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "New Sessions $network_monitor",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tcp_active_sessions_4_tuple",
       "query": "SELECT max(\"active_sessions\") - max(\"finished_sessions\") FROM \"tcp_active_sessions_4_tuple\" WHERE (\"server_ip\" =~ /^$ip$/ OR \"client_ip\" =~ /^$ip$/) AND $timeFilter GROUP BY time($resolution), \"server_ip\", \"client_ip\" fill(none)",
       "select": [
        [
         { "params": [ "active_sessions" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Server MinWin for Active (Open) Session for $ip",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_active_sessions_4_tuple",
       "select": [
        [
         { "params": [ "min_win_server_min" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "client_ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "OR", "key": "server_ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      }
     ]
    },
    {
     "title": "Server ZeroWins for $ip",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_4_tuple",
       "select": [
        [
         { "params": [ "zwins_server" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "client_ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "OR", "key": "server_ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      }
     ]
    },
    {
     "title": "Client MinWin for Active (Open) Session for $ip",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_active_sessions_4_tuple",
       "select": [
        [
         { "params": [ "min_win_client_min" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "client_ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "OR", "key": "server_ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      }
     ]
    },
    {
     "title": "Client ZeroWins for $ip",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_4_tuple",
       "select": [
        [
         { "params": [ "zwins_client" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "client_ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "OR", "key": "server_ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "TCP Session Error Details for $network_monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Retransmissions $network_monitor",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_4_tuple",
       "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$network_monitor$/ ) AND $timeFilter GROUP BY time($resolution), \"server_ip\", \"client_ip\" fill(0)",
       "select": [
        [
         { "params": [ "retransmissions_client" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ],
        [
         { "params": [ "retransmissions_server" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "client_ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "OR", "key": "server_ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      }
     ]
    },
    {
     "title": "SYN Failures for $network_monitor",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_active_sessions_4_tuple",
       "select": [
        [
         { "params": [ "syn_failure" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Missing SYNs for $network_monitor",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_active_sessions_4_tuple",
       "select": [
        [
         { "params": [ "missing_syns" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Client Retransmissions $network_monitor",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_4_tuple",
       "select": [
        [
         { "params": [ "retransmissions_client" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Client Gaps $network_monitor",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_4_tuple",
       "select": [
        [
         { "params": [ "gaps_client" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Client Duplicates $network_monitor",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_4_tuple",
       "select": [
        [
         { "params": [ "duplicates_client" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Client Sequence Errors $network_monitor",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_4_tuple",
       "select": [
        [
         { "params": [ "sequence_errors_client" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Server Retransmissions $network_monitor",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_4_tuple",
       "select": [
        [
         { "params": [ "retransmissions_server" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Server Gaps $network_monitor",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_4_tuple",
       "select": [
        [
         { "params": [ "gaps_server" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Server Duplicates $network_monitor",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_4_tuple",
       "select": [
        [
         { "params": [ "duplicates_server" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Server Sequence Errors $network_monitor",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "server: $tag_server_ip client: $tag_client_ip",
       "groupBy": [
        { "params": [ "$resolution" ], "type": "time" },
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tcp_4_tuple",
       "select": [
        [
         { "params": [ "sequence_errors_server" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Suspect TCP Sesssions for $network_monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "4-Tuple Suspect TCP Sessions  $network_monitor",
     "type": "table",
     "gridPos": { "h": 15, "w": 14, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Packet Per Second $tag_destination_ip",
       "groupBy": [
        { "params": [ "server_ip" ], "type": "tag" },
        { "params": [ "application_port" ], "type": "tag" },
        { "params": [ "client_ip" ], "type": "tag" },
        { "params": [ "server_hostname" ], "type": "tag" },
        { "params": [ "client_hostname" ], "type": "tag" },
        { "params": [ "network_monitor_name" ], "type": "tag" }
       ],
       "measurement": "suspect_tcp_active_sessions_4_tuple",
       "select": [
        [
         { "params": [ "packets_client_session_avg" ], "type": "field" }
        ],
        [
         { "params": [ "packets_server_session_avg" ], "type": "field" }
        ],
        [
         { "params": [ "bytes_server_session_avg" ], "type": "field" }
        ],
        [
         { "params": [ "bytes_client_session_avg" ], "type": "field" }
        ],
        [
         { "params": [ "duration_s_max" ], "type": "field" }
        ],
        [
         { "params": [ "missing_syns" ], "type": "field" }
        ],
        [
         { "params": [ "syn_failure" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    },
    {
     "title": "Suspect Sessions GeoIP $network_monitor",
     "type": "c-packet-networks-network-map",
     "gridPos": { "h": 15, "w": 10, "x": 14, "y": 9 }
    },
    {
     "title": "Test for $network_monitor",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Packet Per Second $tag_destination_ip",
       "groupBy": [
        { "params": [ "source_ip" ], "type": "tag" },
        { "params": [ "application_port" ], "type": "tag" },
        { "params": [ "network_monitor_name" ], "type": "tag" },
        { "params": [ "destination_ip" ], "type": "tag" },
        { "params": [ "ip_protocol_name" ], "type": "tag" }
       ],
       "measurement": "flow_data_4_tuple",
       "select": [
        [
         { "params": [ "bytes_per_s" ], "type": "field" }
        ],
        [
         { "params": [ "packets_per_s" ], "type": "field" }
        ]
       ],
       "slimit": "100",
       "tags": [
        { "key": "network_monitor_name", "operator": "=~", "value": "/^$network_monitor$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Last Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "placeholder",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}