{
 "title": "Latency Network Monitor Level 2 w Sapphire",
 "tags": [
  "Network_Monitor",
  "TCP_Analytics",
  "cPacket",
  "Level 2"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "flow_g",
    "label": "Network Monitor Name",
    "query": "show tag values with key =~ /network_monitor_name|flow_g/"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "show tag values with key =~ /server_ip|server|client_ip/ limit 100 "
   },
   {
    "name": "res",
    "label": "Resolution",
    "query": "1s,2s,5s,10s,15s,30s,1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "indicators",
    "label": "User Defined Filters on indicators"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center style=\"background-color:black;padding:1rem\"><a href=\"http://www.cpacketnetworks.com\" target=\"_new\"><img width=\"220px\" src=\"/static/images/cpacket_white_text.svg\"></a></center>"
   }
  },
  {
   "title": "Session RTT for \"$flow_g\" (By Server)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "persecond",
     "query": "SELECT mean(\"from_srvr_rtt\")+mean(\"to_srvr_rtt\") FROM \"persecond\" WHERE (\"flow_g\" =~ /^$flow_g$/ AND \"dp_type\" = 'eps' AND \"m_type\" = 'flow' AND \"from_srvr_rtt\" > 0) AND $timeFilter GROUP BY \"server\"",
     "select": [
      [
       { "params": [ "from_srvr_rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "from_srvr_rtt", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "$tag_server_ip",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "server_ip" ], "type": "tag" }
     ],
     "measurement": "tcp_4_tuple",
     "query": "SELECT mean(\"rtt_server_s\")+ mean(\"rtt_client_s\") FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/) AND $timeFilter GROUP BY time($interval), \"server_ip\"",
     "select": [
      [
       { "params": [ "rtt_server_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "rtt_client_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    }
   ]
  },
  {
   "title": "Session RTT for \"$flow_g\"",
   "type": "table-old",
   "description": "Session Round Trip Time: The average transit time for packets travelling from the cVu to the server, back to the cVu, to the client and then returning back to the cVu.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "persecond",
     "query": "SELECT mean(\"from_srvr_rtt\")+mean(\"to_srvr_rtt\") as \"Avg\" FROM \"persecond\" WHERE (\"flow_g\" =~ /^$flow_g$/ AND \"m_type\" = 'flow' AND \"dp_type\" = 'eps' AND \"from_srvr_rtt\" > 0) AND $timeFilter GROUP BY \"server\"",
     "select": [
      [
       { "params": [ "from_srvr_rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "from_srvr_rtt", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "$tag_server_ip",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "persecond",
     "query": "SELECT mean(\"rtt_server_s\")+ mean(\"rtt_client_s\") FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/) AND $timeFilter GROUP BY time($interval), \"server_ip\"",
     "select": [
      [
       { "params": [ "from_srvr_rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "from_srvr_rtt", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Session RTT ($server Sessions)",
   "type": "graph",
   "description": "Session Round Trip Time (to server and back, to client and back) for Server $server",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Client: $tag_client",
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "persecond",
     "query": "SELECT mean(\"from_srvr_rtt\")+mean(\"to_srvr_rtt\") FROM \"persecond\" WHERE (\"flow_g\" =~ /^$flow_g$/ AND \"m_type\" = 'flow' AND \"dp_type\" = 'eps' AND \"from_srvr_rtt\" > 0 AND \"server\" =~ /^$server$/) AND $timeFilter GROUP BY time($res), \"server\", \"client\" fill(none)",
     "select": [
      [
       { "params": [ "from_srvr_rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "from_srvr_rtt", "operator": ">", "value": "0" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "Client: $tag_client",
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "persecond",
     "query": "SELECT mean(\"rtt_server_s\")+ mean(\"rtt_client_s\") FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/ and server_ip =~ /$server/) AND $timeFilter GROUP BY time($interval), \"server_ip\"",
     "select": [
      [
       { "params": [ "from_srvr_rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "from_srvr_rtt", "operator": ">", "value": "0" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Server Side RTT for \"$flow_g\" (By Server)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "persecond",
     "select": [
      [
       { "params": [ "from_srvr_rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "from_srvr_rtt", "operator": ">", "value": "0" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" }
     ]
    },
    {
     "alias": "$tag_server_ip",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "persecond",
     "query": "SELECT mean(\"rtt_server_s\") FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/) AND $timeFilter GROUP BY time($interval), \"server_ip\"",
     "select": [
      [
       { "params": [ "from_srvr_rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "from_srvr_rtt", "operator": ">", "value": "0" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" }
     ]
    }
   ]
  },
  {
   "title": "Server Side RTT for \"$flow_g\"",
   "type": "table",
   "description": "Round Trip Time from the cVu to the server and back to the cVu.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "persecond",
     "select": [
      [
       { "params": [ "from_srvr_rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "from_srvr_rtt", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "persecond",
     "query": "SELECT mean(\"rtt_server_s\") FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/) AND $timeFilter GROUP BY  \"server_ip\"",
     "select": [
      [
       { "params": [ "from_srvr_rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "from_srvr_rtt", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Server Side RTT ($server Sessions)",
   "type": "graph",
   "description": "Round Trip Time (to server and back) for Server $server",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Client: $tag_client",
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "persecond",
     "query": "SELECT max(\"from_srvr_rtt\") AS \"from-server\", max(\"to_srvr_rtt\") AS \"to-server\" FROM \"persecond\" WHERE (\"flow_g\" =~ /^$flow_g$/) AND $timeFilter GROUP BY time($res) fill(0)",
     "select": [
      [
       { "params": [ "from_srvr_rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "from_srvr_rtt", "operator": ">", "value": "0" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "Client: $tag_client_ip",
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "persecond",
     "query": "SELECT mean(\"rtt_server_s\") FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/ and server_ip =~ /$server/) AND $timeFilter GROUP BY time($interval), \"server_ip\", \"client_ip\"",
     "select": [
      [
       { "params": [ "from_srvr_rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "from_srvr_rtt", "operator": ">", "value": "0" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time for \"$flow_g\" (By Server)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "persecond",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "response_time", "operator": ">", "value": "0" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" }
     ]
    },
    {
     "alias": "$tag_server_ip",
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "server_ip" ], "type": "tag" }
     ],
     "measurement": "tcp_active_sessions_4_tuple",
     "query": "SELECT mean(\"response_time_s_avg\") FROM \"tcp_active_sessions_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/) AND $timeFilter GROUP BY time($res), \"server_ip\"",
     "select": [
      [
       { "params": [ "response_time_s_avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time for \"$flow_g\"",
   "type": "table-old",
   "description": "The server SYN to SYNACK Response Time.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "persecond",
     "query": "SELECT mean(\"response_time\") FROM \"persecond\" WHERE (\"m_type\" = 'flow' AND \"dp_type\" = 'eps' AND \"flow_g\" =~ /^$flow_g$/) AND $timeFilter GROUP BY time($time_range*2), \"server\", \"client\" fill(none)",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "response_time", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "server_ip" ], "type": "tag" }
     ],
     "measurement": "tcp_active_sessions_4_tuple",
     "query": "SELECT mean(\"response_time_s_avg\") FROM \"tcp_active_sessions_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/) AND $timeFilter GROUP BY time($res), \"server_ip\"",
     "select": [
      [
       { "params": [ "response_time_s_avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time ($server Sessions)",
   "type": "graph",
   "description": "The server (SYN to SYNACK) response time for server $server",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Client: $tag_client",
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "persecond",
     "query": "SELECT max(\"from_srvr_rtt\") AS \"from-server\", max(\"to_srvr_rtt\") AS \"to-server\" FROM \"persecond\" WHERE (\"flow_g\" =~ /^$flow_g$/) AND $timeFilter GROUP BY time($res) fill(0)",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "response_time", "operator": ">", "value": "0" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "Client: $tag_client_ip",
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "persecond",
     "query": "SELECT mean(\"response_time_s_avg\") FROM \"tcp_active_sessions_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/ and server_ip =~ /$server/) AND $timeFilter GROUP BY time($res), \"server_ip\", \"client_ip\"",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "response_time", "operator": ">", "value": "0" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Instructions: How to Use This Dashbaord",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency for Network Monitor \"$flow_g\"",
     "type": "text",
     "gridPos": { "h": 5, "w": 13, "x": 0, "y": 25 },
     "content": "#### Usage Notes:\n- The panels are filterd by the selected Network Monitor: $flow_g\n- When following links, the Network Monitor selection ($flow_g) will also be applied to the Linked Dashboard\n- When following links, the Server selected in the pull down menu ($server) will be passed to the Linked Dashboard\n- User Defined Filters on indicators: Adds dashboard filters to narrow down the view (the Linked Dashboard may also be affected)\n- If you don't want the \"User Defined Filters\" to apply to Linked Dashboards, then clear these filters before clicking a link.\n\n"
    }
   ]
  }
 ]
}