{
 "title": "TCP Health Level 1 w Sapphire",
 "tags": [
  "Summary",
  "TCP_Analytics",
  "Level 1",
  "cPacket"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "flow_g",
    "label": "Network Monitors to Display",
    "query": "show tag values with key =~ /flow_g|network_monitor_name/"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center style=\"background-color:black;padding:1rem\"><a href=\"http://www.cpacketnetworks.com\" target=\"_new\"><img width=\"220px\" src=\"/static/images/cpacket_white_text.svg\"></a></center>"
   }
  },
  { "title": "Single Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "$flow_g Response Time",
   "type": "stat",
   "description": "The largest \"average Syn to SynAck Response Time\" measured for any server associated with the Network Monitor $flow_g.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "repeat": "flow_g",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "flow_g" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "persecond",
     "query": "SELECT MAX(\"response_time\") FROM\n(\n    SELECT MEAN(\"response_time\") as \"response_time\" FROM \"persecond\"\n    WHERE (\"m_type\" = 'flow' AND \"dp_type\" = 'eps' AND \"flow_g\" =~ /^$flow_g$/ AND \"response_time\" > 0) AND $timeFilter\n    GROUP BY \"flow_g\", \"server\" FILL(none)\n)\nWHERE $timeFilter FILL(0)",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "network_monitor_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_active_sessions_4_tuple",
     "query": "SELECT MAX(\"response_time\") FROM\n(\n    SELECT MEAN(\"response_time\") as \"response_time\" FROM \"persecond\"\n    WHERE (\"m_type\" = 'flow' AND \"dp_type\" = 'eps' AND \"flow_g\" =~ /^$flow_g$/ AND \"response_time\" > 0) AND $timeFilter\n    GROUP BY \"flow_g\", \"server\" FILL(none)\n)\nWHERE $timeFilter FILL(0)",
     "select": [
      [
       { "params": [ "response_time_s_avg" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    }
   ]
  },
  {
   "title": "$flow_g Round Trip Time",
   "type": "stat",
   "description": "The largest \"average Round Trip Time\" measured for any server TCP session associated with the Network Monitor $flow_g.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "repeat": "flow_g",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "flow_g" ], "type": "tag" }
     ],
     "measurement": "persecond",
     "query": "SELECT MAX(\"rtt\") FROM\n(\n    SELECT MEAN(\"from_srvr_rtt\") + MEAN(\"to_srvr_rtt\") as \"rtt\" FROM \"persecond\"\n    WHERE (\"m_type\" = 'flow' AND \"dp_type\" = 'eps' AND \"flow_g\" =~ /^$flow_g$/ AND \"from_srvr_rtt\" > 0) AND $timeFilter\n    GROUP BY \"flow_g\", \"server\" FILL(none)\n)\nWHERE $timeFilter FILL(0)",
     "select": [
      [
       { "params": [ "from_srvr_rtt" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_4_tuple",
     "query": "SELECT MAX(\"rtt\") from \n( \n    SELECT mean(\"rtt_client_s\") + mean(\"rtt_server_s\") as \"rtt\" FROM \"tcp_4_tuple\" \n    WHERE (\"network_monitor_name\" =~ /^$flow_g$/) AND $timeFilter \n    GROUP BY time($__interval) fill(null)\n)",
     "select": [
      [
       { "params": [ "rtt_client_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "rtt_server_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    }
   ]
  },
  {
   "title": "$flow_g Zero Windows",
   "type": "stat",
   "description": "The largest number of (client and server) zero windows for any server associated with the Network Monitor $flow_g.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "repeat": "flow_g",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "persecond",
     "query": "SELECT MAX(\"zwins\") FROM\n(\n    SELECT SUM(\"from_srvr_zwins\") + SUM(\"to_srvr_zwins\") as \"zwins\" FROM \"persecond\"\n    WHERE (\"m_type\" = 'flow' AND \"dp_type\" = 'eps' AND \"flow_g\" =~ /^$flow_g$/) AND $timeFilter\n    GROUP BY \"flow_g\", \"server\" FILL(0)\n)\nWHERE $timeFilter FILL(0)",
     "select": [
      [
       { "params": [ "from_srvr_zwins" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "to_srvr_zwins" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_4_tuple",
     "query": "SELECT sum(\"zwins_client\") + sum(\"zwins_server\") FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "zwins_client" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "zwins_server" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    }
   ]
  },
  {
   "title": "$flow_g Retransmissions",
   "type": "stat",
   "description": "The largest number of (client and server) retransmissions for any server associated with the Network Monitor $flow_g.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "repeat": "flow_g",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "persecond",
     "query": "SELECT MAX(\"retrans\") FROM\n(\n    SELECT SUM(\"from_srvr_retrans\") + SUM(\"to_srvr_retrans\") as \"retrans\" FROM \"persecond\"\n    WHERE (\"m_type\" = 'flow' AND \"dp_type\" = 'eps' AND \"flow_g\" =~ /^$flow_g$/) AND $timeFilter\n    GROUP BY \"flow_g\", \"server\" FILL(0)\n)\nWHERE $timeFilter FILL(0)",
     "select": [
      [
       { "params": [ "from_srvr_retrans" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_4_tuple",
     "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "retransmissions_client" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "retransmissions_server" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    }
   ]
  },
  {
   "title": "$flow_g SYN Errors",
   "type": "stat",
   "description": "The largest number of \"failed SYN and missing SYN\" events counted for any server associated with the Network Monitor $flow_g.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "repeat": "flow_g",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "persecond",
     "query": "SELECT MAX(\"syn_errors\") FROM\n(\n    SELECT SUM(\"missing_syn\") + SUM(\"fail_syn\") as \"syn_errors\" FROM \"persecond\"\n    WHERE (\"m_type\" = 'flow' AND \"dp_type\" = 'eps' AND \"flow_g\" =~ /^$flow_g$/) AND $timeFilter\n    GROUP BY \"flow_g\", \"server\" FILL(0)\n)\nWHERE $timeFilter FILL(0)\n\n",
     "select": [
      [
       { "params": [ "missing_syn" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_active_sessions_4_tuple",
     "query": "SELECT sum(\"missing_syns\") + sum(\"syn_failures\") FROM \"tcp_active_sessions_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "missing_syns" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "syn_failures" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    }
   ]
  },
  {
   "title": "$flow_g New Sessions",
   "type": "stat",
   "description": "The most \"new sessions\" established for any server associated with the Network Monitor $flow_g.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "repeat": "flow_g",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "persecond",
     "query": "SELECT MAX(\"sessions\") FROM\n(\n    SELECT SUM(\"new_sessions\") as \"sessions\" FROM \"persecond\"\n    WHERE (\"m_type\" = 'flow' AND \"dp_type\" = 'eps' AND \"flow_g\" =~ /^$flow_g$/) AND $timeFilter\n    GROUP BY \"flow_g\", \"server\" FILL(0)\n)\nWHERE $timeFilter FILL(0)",
     "select": [
      [
       { "params": [ "active_sessions" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_active_sessions_4_tuple",
     "select": [
      [
       { "params": [ "active_sessions" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    }
   ]
  }
 ]
}