{
 "title": "TCP Errors Network Monitor Level 2 w Sapphire",
 "tags": [
  "TCP_Analytics",
  "Network_Monitor",
  "cPacket",
  "Level 2"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "flow_g",
    "label": "Network Monitor Name",
    "query": "show tag values with key =~ /flow_g|network_monitor_name/"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "show tag values with key =~ /server|server_ip|client_ip/  limit 100 "
   },
   {
    "name": "res",
    "label": "Resolution",
    "query": "1s,2s,5s,10s,15s,30s,1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "indicators",
    "label": "User Defined Filters on indicators"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center style=\"background-color:black;padding:1rem;\"><a href=\"http://www.cpacketnetworks.com\" target=\"_new\"><img width=\"220px\" src=\"/static/images/cpacket_white_text.svg\"></a></center>"
   }
  },
  { "title": "Retransmissions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Session Retransmissions for \"$flow_g\" (By Server)",
   "type": "grafana-piechart-panel",
   "description": "Client + Server Retransmissions for sessions in $flow_g, grouped by server",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "persecond",
     "query": "SELECT sum(\"from_srvr_retrans\")+sum(\"to_srvr_retrans\") FROM \"persecond\" WHERE (\"m_type\" = 'flow' AND \"dp_type\" = 'eps' AND \"flow_g\" =~ /^$flow_g$/) AND $timeFilter GROUP BY \"server\"",
     "select": [
      [
       { "params": [ "from_srvr_retrans" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "from_srvr_retrans", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "$tag_server_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server_ip" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_4_tuple",
     "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/) AND $timeFilter GROUP BY time($__interval), \"server_ip\" fill(null)",
     "select": [
      [
       { "params": [ "retransmissions_client" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "retransmissions_server" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    }
   ]
  },
  {
   "title": "Session Retransmissions for \"$flow_g\"",
   "type": "table",
   "description": "Server + Client Retransmissions for $flow_g conversations",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "alias": "$tag_client $tag_server",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "persecond",
     "query": "SELECT SUM(\"from_srvr_retrans\") + SUM(\"to_srvr_retrans\") AS \"Total\" FROM \"persecond\" WHERE (\"flow_g\" =~ /^$flow_g$/ AND \"m_type\" = 'flow' AND \"dp_type\" = 'eps') AND $timeFilter GROUP BY \"server\", \"client\"",
     "select": [
      [
       { "params": [ "from_srvr_retrans" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" }
     ]
    },
    {
     "alias": "$tag_client $tag_server",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "persecond",
     "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/) AND $timeFilter GROUP BY time($__interval), \"server_ip\" fill(null)",
     "select": [
      [
       { "params": [ "from_srvr_retrans" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" }
     ]
    }
   ]
  },
  {
   "title": "Session Retransmissions ($server Sessions)",
   "type": "graph",
   "description": "The number of (client and server) retransmissions for sessions with server $server, grouped by client.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Client: $tag_client",
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "persecond",
     "query": "SELECT max(\"from_srvr_rtt\") AS \"from-server\", max(\"to_srvr_rtt\") AS \"to-server\" FROM \"persecond\" WHERE (\"flow_g\" =~ /^$flow_g$/) AND $timeFilter GROUP BY time($res) fill(0)",
     "select": [
      [
       { "params": [ "from_srvr_retrans" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "Client: $tag_client_ip",
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tcp_4_tuple",
     "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/ and server_ip =~ /$server/) AND $timeFilter GROUP BY time($__interval), \"server_ip\", \"client_ip\" fill(null)",
     "select": [
      [
       { "params": [ "from_srvr_retrans" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Server Retransmissions for \"$flow_g\" (By Server)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "persecond",
     "select": [
      [
       { "params": [ "from_srvr_retrans" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" }
     ]
    },
    {
     "alias": "$tag_server_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"retransmissions_client\")  FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/) AND $timeFilter GROUP BY time($__interval), \"server_ip\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Server Retransmissions for \"$flow_g\"",
   "type": "table-old",
   "description": "Server Retransmissions for $flow_g conversations",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "persecond",
     "select": [
      [
       { "params": [ "from_srvr_retrans" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" }
     ]
    },
    {
     "alias": "$tag_server_ip",
     "groupBy": [
      { "params": [ "server_ip" ], "type": "tag" }
     ],
     "measurement": "tcp_4_tuple",
     "select": [
      [
       { "params": [ "retransmissions_server" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    }
   ]
  },
  {
   "title": "Server Retransmissions (By Client)",
   "type": "graph",
   "description": "The number of server retransmissions, grouped by client.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Client: $tag_client",
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "persecond",
     "query": "SELECT max(\"from_srvr_rtt\") AS \"from-server\", max(\"to_srvr_rtt\") AS \"to-server\" FROM \"persecond\" WHERE (\"flow_g\" =~ /^$flow_g$/) AND $timeFilter GROUP BY time($res) fill(0)",
     "select": [
      [
       { "params": [ "from_srvr_retrans" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "Client: $tag_client_ip",
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "persecond",
     "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/ and \"server_ip\" =~ /$server/) AND $timeFilter GROUP BY time($__interval), \"server_ip\", \"client_ip\" fill(none)",
     "select": [
      [
       { "params": [ "from_srvr_retrans" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Client Retransmissions for \"$flow_g\" (By Clientr)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "persecond",
     "select": [
      [
       { "params": [ "to_srvr_retrans" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" }
     ]
    },
    {
     "alias": "$tag_client_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"retransmissions_client\")  FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/) AND $timeFilter GROUP BY time($__interval), \"client_ip\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Client Retransmissions for \"$flow_g\"",
   "type": "table-old",
   "description": "Client Retransmissions for $flow_g conversations",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "alias": "$tag_client",
     "groupBy": [
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "persecond",
     "select": [
      [
       { "params": [ "to_srvr_retrans" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" }
     ]
    },
    {
     "alias": "$tag_server_ip",
     "groupBy": [
      { "params": [ "server_ip" ], "type": "tag" }
     ],
     "measurement": "tcp_4_tuple",
     "select": [
      [
       { "params": [ "retransmissions_client" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    }
   ]
  },
  {
   "title": "Client Retransmissions ($server Sessions)",
   "type": "graph",
   "description": "The number of client retransmissions for sessions with server $server.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Client: $tag_client",
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "persecond",
     "query": "SELECT max(\"from_srvr_rtt\") AS \"from-server\", max(\"to_srvr_rtt\") AS \"to-server\" FROM \"persecond\" WHERE (\"flow_g\" =~ /^$flow_g$/) AND $timeFilter GROUP BY time($res) fill(0)",
     "select": [
      [
       { "params": [ "to_srvr_retrans" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "Client: $tag_client_ip",
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "persecond",
     "query": "SELECT sum(\"retransmissions_client\") + sum(\"retransmissions_server\") FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/ and \"server_ip\" =~ /$server/) AND $timeFilter GROUP BY time($__interval), \"server_ip\", \"client_ip\" fill(null)",
     "select": [
      [
       { "params": [ "to_srvr_retrans" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Zero Windows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Session Zero Windows for \"$flow_g\" (By Server)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "persecond",
     "query": "SELECT sum(\"from_srvr_zwins\")+sum(\"to_srvr_zwins\") FROM \"persecond\" WHERE (\"flow_g\" =~ /^$flow_g$/ AND \"m_type\" = 'flow' AND \"dp_type\" = 'eps') AND $timeFilter GROUP BY \"server\"",
     "select": [
      [
       { "params": [ "from_srvr_zwins" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "from_srvr_zwins", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "$tag_server_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server_ip" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp_4_tuple",
     "query": "SELECT sum(\"zwins_client\") + sum(\"zwins_client\") FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/) AND $timeFilter GROUP BY time($__interval), \"server_ip\" fill(null)",
     "select": [
      [
       { "params": [ "zwins_client" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "zwins_client" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    }
   ]
  },
  {
   "title": "Session Zero Windows for \"$flow_g\"",
   "type": "table-old",
   "description": "Client + Server Zero Window counts for sessions in $flow_g",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "persecond",
     "select": [
      [
       { "params": [ "from_srvr_zwins" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" }
     ]
    },
    {
     "alias": "$tag_server_ip",
     "groupBy": [
      { "params": [ "server_ip" ], "type": "tag" }
     ],
     "measurement": "tcp_4_tuple",
     "query": "SELECT \"zwins_client\" + \"zwins_server\" FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/) AND $timeFilter GROUP BY \"server_ip\"",
     "select": [
      [
       { "params": [ "zwins_client" ], "type": "field" }
      ],
      [
       { "params": [ "zwins_server" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "network_monitor_name", "operator": "=~", "value": "/^$flow_g$/" }
     ]
    }
   ]
  },
  {
   "title": "Session ZWins for $server",
   "type": "graph",
   "description": "The number of (client and server) zero windows for sessions with server $server, grouped by client.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Client: $tag_client",
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "persecond",
     "query": "SELECT sum(\"from_srvr_zwins\")+sum(\"to_srvr_zwins\") FROM \"persecond\" WHERE (\"flow_g\" =~ /^$flow_g$/ AND \"m_type\" = 'flow' AND \"dp_type\" = 'eps' AND \"server\" =~ /^$server$/) AND $timeFilter GROUP BY time($res), \"server\", \"client\" fill(none)",
     "select": [
      [
       { "params": [ "from_srvr_zwins" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "from_srvr_zwins", "operator": ">", "value": "0" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "Client: $tag_client_ip",
     "groupBy": [
      { "params": [ "$res" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "persecond",
     "query": "SELECT sum(\"zwins_client\") + sum(\"zwins_client\") FROM \"tcp_4_tuple\" WHERE (\"network_monitor_name\" =~ /^$flow_g$/ AND server =~ /$server/ ) AND $timeFilter GROUP BY time($__interval), \"server_ip\", \"client_ip\" fill(null)",
     "select": [
      [
       { "params": [ "from_srvr_zwins" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flow_g", "operator": "=~", "value": "/^$flow_g$/" },
      { "condition": "AND", "key": "m_type", "operator": "=", "value": "flow" },
      { "condition": "AND", "key": "dp_type", "operator": "=", "value": "eps" },
      { "condition": "AND", "key": "from_srvr_zwins", "operator": ">", "value": "0" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  }
 ]
}